# Generated by Django 3.0.5 on 2022-04-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.CharField(default='dumy value', max_length=50),
            preserve_default=False,
        ),
    ]
