# Generated by Django 3.0.5 on 2022-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_card_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_text',
            field=models.CharField(max_length=150),
        ),
    ]
