# Generated by Django 3.0.5 on 2022-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='asset_value',
            field=models.CharField(default='30000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.CharField(default='40000', max_length=10),
            preserve_default=False,
        ),
    ]
