# Generated by Django 3.0.5 on 2022-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20220224_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='card_text',
            field=models.CharField(default='dummy', max_length=50),
            preserve_default=False,
        ),
    ]
