# Generated by Django 3.0.5 on 2022-04-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_loanrecord_card_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrecord',
            name='card_text',
        ),
    ]
