# Generated by Django 4.0.2 on 2022-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_remove_loanrecord_card_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('Dependents', models.IntegerField(default=0)),
                ('Applicantincome', models.IntegerField(default=0)),
                ('Coapplicatincome', models.IntegerField(default=0)),
                ('LoanAmount', models.IntegerField(default=0)),
                ('Loan_Amount_Term', models.IntegerField(default=0)),
                ('Credit_History', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('Married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150)),
                ('Education', models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], max_length=150)),
                ('Self_Employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=150)),
                ('Property_Area', models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], max_length=150)),
            ],
        ),
    ]
